---
title: "p8105-data_wrangling-tidy_data"
author: "Yuqi Miao"
date: "12/23/2019"
output: html_document
---
```{r}
library(tidyverse)
options(tibble.print_min = 5)
```

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
    janitor::clean_names()

```

## pivot_longer

collect spreading var in column names.

```{r}
pulse_tidy_data = pulse_data %>% 
    pivot_longer(names_to = "visit", cols = bdi_score_bl:bdi_score_12m, values_to = "bdi_score",names_prefix ="bdi_score_" ) %>% 
    select(id, visit, everything()) %>% 
    mutate(
        visit = factor(
            visit, 
            levels = c("bl","01m","06m","12m"), 
            labels = c("00m","01m","06m","12m") 
            ## also, use replace(visit, visit == "bl", "00m") to change row names
            )
    )

?replace

```


## seperate columns

```{r}
litters_data = read_csv(file = "data/FAS_litters.csv") %>% 
    janitor::clean_names()

litters_data %>% count(group)


litters_data = litters_data %>% 
    separate(
        group,
        into = c("dose","day_of_tr"),
        sep = 3
    ) %>% 
    mutate(
        dose = str_to_lower(dose),
        wt_gain = gd18_weight - gd0_weight
        ) %>% 
    arrange(litter_number)

```


## pivot_wider

```{r}
analysis_result = tibble(
    group = rep(c("treat","placebo"),each = 2),
    time = rep(c("pre","post"),2),
    mean = 1:4
)

analysis_result %>% 
    pivot_wider(
        names_from = time,
        values_from = mean
    ) ## 2*2 table
```

## bind rows

```{r}
fr = readxl::read_excel("data/LotR_Words.xlsx", range ="B3:D6") %>% 
    mutate(movie = "fellowship_ring")
tt= readxl::read_excel("data/LotR_Words.xlsx", range ="F3:H6") %>% 
    mutate(movie = "two_towers")
rk = readxl::read_excel("data/LotR_Words.xlsx", range ="J3:L6") %>% 
    mutate(movie = "return_king")
```

```{r}
ltr_tidy = bind_rows(fr,tt,rk) %>% 
    janitor::clean_names() %>% 
    pivot_longer(
        female:male,
        names_to = "sex",
        values_to = "words"
    )
```


## join data

```{r}
pup_data = read_csv("data/FAS_pups.csv",col_types = "ciiiii") %>% 
    janitor::clean_names() %>% 
    mutate(sex = recode(sex, `1` = "male", `2` = "female"))
litters_data = read_csv("data/FAS_litters.csv", col_types ="cciiiiii") %>% 
    janitor::clean_names()

fas_data = left_join(pup_data, litters_data)

dim(pup_data)
dim(litters_data)
dim(fas_data)
    
```











